apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- "deployment.yaml"
images:
- name: "app-image"
  newName: "docker.io/marcelloale/nodejs_demo_image"
  newTag: "initial"
namespace: "cloud"
